export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_DATA = 'FETCH_DATA';
export const LIKE = 'LIKE';

export const FETCH_PROCESSED_TICKER_LIST = 'FETCH_PROCESSED_TICKER_LIST';
export const FETCH_CLICKED_SOURCE = 'FETCH_CLICKED_SOURCE';

export const FETCH_CLICKED_TICKER = 'FETCH_CLICKED_TICKER';
export const FETCH_SOURCE_LIST = 'FETCH_SOURCE_LIST';
