export const financialsToLabel = {
    // maxAge:,
    currentPrice: "Current Price",
    recommendationKey: "Analyst Recommendation",
    financialCurrency: "Financial Currency",
    targetHighPrice: "Target High Price",
    targetLowPrice: "Target Low Price",
    targetMeanPrice: "Target Mean Price",
    // targetMedianPrice: "Target Median Price",
    // recommendationMean: "Recommendation Mean",
    // numberOfAnalystOpinions:,
    totalCash: "Total Cash",
    totalCashPerShare: "Total Cash Per Share",
    ebitda: "EBITDA",
    totalDebt: "Total Debt",
    quickRatio: "Quick Ratio",
    currentRatio: "Current Ratio",
    totalRevenue: "Total Revenue",
    debtToEquity: "Debt To Equity",
    revenuePerShare: "Revenue Per Share",
    returnOnAssets: "Return On Assets",
    returnOnEquity: "Return On Equity",
    grossProfits: "Gross Profits",
    freeCashflow: "Free Cash Flow",
    // operatingCashflow: "Operating Cash Flow",
    revenueGrowth: "Revenue Growth",
    // grossMargins: "Gross Margins",
    // ebitdaMargins: "EBITDA Margins",
    // operatingMargins: "Operating Margins",
    // profitMargins: "Profit Margins",
    }

export const keyStatisticsToLabel = {
    // "maxAge": 1,
    // "forwardPE": "Forward PE",
    // "profitMargins": -0.08456001,
    "floatShares": "Float Shares",
    "sharesOutstanding": "Shares Outstanding",
    "sharesShort": "Shares Short",
    "sharesShortPriorMonth": "Shares Short Prior Month",
    "heldPercentInsiders": "Insider Holdings (%)",
    "heldPercentInstitutions": "Institution Holdings (%)",
    "shortRatio": "Short Ratio",
    "shortPercentOfFloat": "Short Percent of Float",
    // "beta": 1.15078,
    // "category": null,
    "bookValue": "Book Value",
    "priceToBook": "Price To Book",
    // "fundFamily": null,
    // "legalType": null,
    // "lastFiscalYearEnd": 2016-09-24T00:00:00.000Z,
    // "nextFiscalYearEnd": 2018-09-24T00:00:00.000Z,
    // "mostRecentQuarter": 2017-04-01T00:00:00.000Z,
    // "netIncomeToCommon": -722924032,
    "trailingEps": "Trailing EPS",
    "forwardEps": "Forward EPS",
    "pegRatio": "PEG Ratio",
    // "lastSplitFactor": "2/1",
    // "lastSplitDate": 2014-06-09T00:00:00.000Z,
    // "52WeekChange": 0.44787717,
    // "SandP52WeekChange": 0.15511417
    }

    export const recommendationToLabel = {
        "strongSell": "Strong Sell",
        "sell": "Sell",
        "hold": "Hold",
        "buy": "Buy",
        "strongBuy": "Strong Buy"
      }
      