name: CI deploy
on:
    push:
        branches: [master]
env:
    AWS_HOST: 54.180.26.58
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.15.5'
            - name: Build Client
              env:
                  NODE_ENV: development
              run: |
                  cd frontend
                  npm ci
                  npm run build
            - name: Build Server
              env:
                  NODE_ENV: development
              run: |
                  cd backend
                  npm ci
            - name: Deploy on servers
              env:
                  DEPLOYMENT_KEY_B64: ${{ secrets.DEPLOYMENT_KEY_B64 }}
              run: |
                  mkdir ~/.ssh;
                  touch ~/.ssh/known_hosts;
                  ssh-keyscan $AWS_HOST >> ~/.ssh/known_hosts;
                  echo $DEPLOYMENT_KEY_B64 | base64 -d > ~/.ssh/id_rsa;
                  chmod 644 ~/.ssh/known_hosts;
                  chmod 600 ~/.ssh/id_rsa;
                  chmod 0755 ./.github/workflows/deploy.sh;
                  ./.github/workflows/deploy.sh;
                  rm -rf ~/.ssh;